### ISSUE TITLE
Multislider Styling

### ISSUE THREAD

**Issue by AndrejHronco** [nexus-js/ui#104]
some of the styling options for the multislider seem to have disappeared in v2. in v1, there was a nice auto-styling of alternating slider colors in groups of 3. These styles don't seem to be part of v2 [accenthl, border, borderhl] and I think those are the styles I want to set.

Is there a way to get the multislider to look like v1 or would i have to manually set the rect and circle elements to the desired colors?

Thank you, love using Nexus UI

**Comment by taylorbf** [comment]
There is not currently a way to do candycane styling on a multislider, except for addressing the svg elements individually as you said. Sorry! In v2 that was a feature I put on hold in favor of other functionality needs. I will leave this open and look to add it in the next update.

**Comment by tatecarson** [comment]
This is back with 2.0.10, though it isn't documented. It should work the same way as before.
