### ISSUE TITLE
on change for a group of controls

### ISSUE THREAD

**Issue by brucelane** [nexus-js/ui#108]
Hi,
how can I set a unique id on each control and then have a common 'on change' for all of them to use this unique id?

For now, I haven't found a way to loop on the controls so I do:
```
var dialArray = [];
for (var i = 0; i < 16; i++) {
  dialArray.push(new Nexus.Add.Dial('#target', {
    size: [100, 100],
    value: i * 0.1
  }));
}
// red
dialArray[0].colorize("accent", "#f00");
dialArray[0].on('change', function (data) {
  if (window.socket) window.socket.send('{"params" :[{"name" : ' + 1 + ',"value" :' + data + "}]}");
});
// green
dialArray[1].colorize("accent", "#0f0");
dialArray[1].on('change', function (data) {
  if (window.socket) window.socket.send('{"params" :[{"name" : ' + 2 + ',"value" :' + data + "}]}");
});
// blue
dialArray[2].colorize("accent", "#00f");
dialArray[2].on('change', function (data) {
  if (window.socket) window.socket.send('{"params" :[{"name" : ' + 3 + ',"value" :' + data + "}]}");
}); 
etc for the 16 dials
```
Is there a better way?

**Comment by taylorbf** [comment]
Hi Bruce,

Yes definitely want to avoid the copy pasting. Two options for this.

## Option 1: bind

First option is to use `.bind()` to bind `i` as a parameter of the callback. 
This is a great technique to know, regardless, and MDN or elsewhere can give you a better description of `bind` than I ever could. Basic code here is:

```js
// assuming this dial is created in a loop....
dial.on('change', function (index,data) {
    console.log( index, data );
}.bind( dial, i ));
```

[Codepen](https://codepen.io/taylorbf/pen/Leppzr)

See the Codepen console for output. There is a button on the bottom left to open the Codepen console if it is not already open.

But there is actually a cleaner way...

## Option 2: this (recommended)

Inside any event function in NexusUI, `this` will refer to the interface that called the event. So in your example, using `this.value` in a dial's event callback would return the value of the dial.

I'd recommend adding `i` as an `index` property of your dial and then retrieving it within the callback as `this.index`

[Codepen](https://codepen.io/taylorbf/pen/EoVVBp?editors=0011)

See the console for output.

Hope this helps! I hadn't really considered this case but it's a useful technique. It should be added to the docs. @mscottnelson ?

**Comment by brucelane** [comment]
great, thank you very much!
