### ISSUE TITLE
TextButton alternate state wrongly documented.

### ISSUE THREAD

**Issue by khoin** [nexus-js/ui#110]
Hello, 

I'm using Nexus for a project. I want to make a TextButton be a toggler, so I followed the documentation here: http://nexus-js.github.io/ui/api/#TextButton

The property `alternateText` when passed into the initiator does not reflect that the button will change to that text when clicked nor will it automatically set the button to toggle.

Setting `alternate` to true does not make the button toggle, but it sets the alternate text to whatever's given to `alternate`. 

What I did was using `{mode : "toggle", alternate: "TextToDisplay"}` instead.

Hope this will be addressed.

**Comment by mscottnelson** [comment]
This is a bug. When using the 'alternateText' property after an object has been created, Nexus currently works as described in doc. However, as you said, the initiator does work the same way. Assigning myself this problem to fix

**Comment by mscottnelson** [comment]
In version 2.0.5, the 'alternate' property is deprecated. Using it now sets the 'alternateText' property.
