### ISSUE TITLE
Nexus.Select.defineOptions fault UI updating. 

### ISSUE THREAD

**Issue by khoin** [nexus-js/ui#111]
Hello,

When you call `Nexus.Select.defineOptions([...stuff])`, the internal data is updated correctly, but the UI is not updated correctly. Thus, on.('change', ...) will not be resolved correctly.

internal data aka `Nexus.Select._options` is correct.

To test this, simply create a Nexus.Select element and call defineOptions method a couple of times (or just once, even).

**Comment by khoin** [comment]
I think this should be the solution: 
https://stackoverflow.com/a/3364546/2076075

Relevant source to apply fix: https://github.com/nexus-js/ui/blob/master/lib/interfaces/select.js#L118-L131

**Comment by taylorbf** [comment]
Great catch! Finally fixed this in e3e9195 .  I did have a loop to remove items but the loop's maximum was a pointer to a number that could change, so the loop was not guaranteed to complete.
