### ISSUE TITLE
Sequencer muting/soloing rows

### ISSUE THREAD

**Issue by nebrekab** [nexus-js/ui#122]
Is there a recommended approach to set blocks to be muted or soloed?

Initial thoughts:

*mute of a row*
1. store the current row sequence
2. update the sequencer's matrix, setting all of the row's values to false

*unmute row*
1. retrieve the stored rows sequence
2. update the sequencer's matrix, setting all of the row's values to stored values

*solo of a row*
1. store all other row sequences
2. update the sequencer's matrix, setting all other row's values to false

*unsolo row*
1. retrieve the stored other rows sequences
2. update the sequencer's matrix, setting all of the other row's values to their stored values

Is this the best approach?

**Comment by taylorbf** [comment]
This is a very cool idea! Again, sorry to have not responded at the time.

What you said makes perfect sense, sure.

I suppose another way would be to add conditionals in the event listeners. Something like:

```js
sequencer.on( 'step', function( column ) {
    if (!row1IsMuted) {
       // synth plays note using column[0] data
    }
    if (!row2IsMuted) {
       // synth plays note using column[1] data
    }
})
```

Certainly you could wrap this up in a for loop to make it nicer. Maybe even turn your `mute` variable into an array, one item for each row of the sequencer. 

But yes either approach would work!
