### ISSUE TITLE
Envelope Editor - Stop addition of new points

### ISSUE THREAD

**Issue by starfishmod** [nexus-js/ui#123]
Currently the Envelope editor will add new points every time you click the background. I would like to be able to stop this from occurring as I have a fixed amount of points in the envelope editor.

**Comment by luisArandas** [comment]
I am not able to change that. I would like to set noNewPoints also.
Can someone help?
Best Luis

**Comment by taylorbf** [comment]
Thanks both of you for the PRs! I just merged the `noNewPoints` settings update from @starfishmod and will publish once I have gone through some of the other issues.
