### ISSUE TITLE
Piano does not fire events

### ISSUE THREAD

**Issue by botway** [nexus-js/ui#126]
Looks like there's a bug in piano module events, this example does not log anything:
```
piano.on('change',function(v) {
  console.log(v);
})
```
other events like "click" or "release" do not work with piano either.

**Comment by taylorbf** [comment]
Hello, sorry to take so long to get back!

I haven't been able to duplicate this error. Is another HTML element covering up the piano and interfering with the mouse clicks?

Here is a codepen that demonstrates a working piano. Let me know if this works for you.

[https://codepen.io/taylorbf/pen/WLwwqb?editors=1111]()

**Comment by botway** [comment]
Hey, thanks - yes now it works :)
    Am Freitag, 14. Dezember 2018, 19:03:03 MEZ hat Ben Taylor <notifications@github.com> Folgendes geschrieben:  
 
 
Hello, sorry to take so long to get back!

I haven't been able to duplicate this error. Is another HTML element covering up the piano and interfering with the mouse clicks?

Here is a codepen that demonstrates a working piano. Let me know if this works for you.

https://codepen.io/taylorbf/pen/WLwwqb?editors=1111
