### ISSUE TITLE
How would I be able to use the Meter interface without audio?

### ISSUE THREAD

**Issue by KittenVillage** [nexus-js/ui#128]
Hi! I'm a bit of a novice, just starting to build my project, and NexusUI seems the perfect fit for it. Except I know I'll need to display a meter from midi data, (0-127) not in a WebAudio context. Is there an easy way to do this?

**Comment by taylorbf** [comment]
Hello! Sorry to take so long to get back!

I would suggest maybe using a slider to visualize that data. The meter interface is really only suited for analyzing audio.

Here is a codepen that shows how to use a slider to visualize a data stream (in this case, just a stream of random numbers)

[https://codepen.io/taylorbf/pen/XoddBN](https://codepen.io/taylorbf/pen/XoddBN)
