### ISSUE TITLE
Sequencer Measures?

### ISSUE THREAD

**Issue by nebrekab** [nexus-js/ui#129]
Hi,

Can you advise on approach to using multiple measures with the Sequencer? is this possible out of the box? Or should something custom be crafted? For example, can you create a 32 column sequencer that is used to playback 2 x measures (of 16). 

Thank you

**Comment by taylorbf** [comment]
There is no way to do this out of the box. But you can use the sequencer's API to create this kind of engine yourself.

The best way to do this I think would be to create two sequencers of 16 columns each. Then, create your own metronome (using whatever web audio lib you are using for your sound engine). On each beat of the metronome, call `.next()` on both of your sequencers. This way you can know that they will always be in sync. 

I suppose another way would be to use the callback of the first sequencer to call `.next()` on the second sequencer -- that would be another way to keep them in sync.

There is actually a ton you can do by manually scrubbing through the sequencer. If you have a sequencer called `sequencer`, then you can do:

```js
sequencer.matrix.column(5)
```

and it will return an array with the data from that column. So you can very easily scrub through the sequencer using your own logic to create as many different sections as you want to. Check out the [matrix](https://nexus-js.github.io/ui/api/#matrix) docs in the API for more on it.
