### ISSUE TITLE
All Atributes of Widgets

### ISSUE THREAD

**Issue by luisArandas** [nexus-js/ui#130]
Is it possible to round the corders of the widgets?
Best, Luis

**Comment by taylorbf** [comment]
Yes it's possible. The API does not include any shortcuts for doing so. But there are a couple different ways to do this in practice --

### CSS:

```css
[nexus-ui] {
  border-radius: 10px;
  overflow:hidden;
}
```

Every NexusUI component has a `nexus-ui` HTML attribute, which you can use as a CSS selector to select all components. 

Here we set the border radius to 10px and then also need to set overflow to hidden, to hide the parts of the interface (most likely SVG) that is drawn in the corners. In other words, this sets the border radius of the interface element's *container*, not the SVG element itself.

### JS:

In JS you can access the interface's HTML element using the `element` or `parent` properties.

```js
var position = new Nexus.Add.Position('#target',{
   size: [200,200]
})

// this sets the border radius of the SVG element itself
position.element.style.borderRadius = "10px"

// or, this sets the border radius of the container, as we did in the CSS above
position.parent.style.borderRadius = "10px"
position.parent.style.overflow = "hidden"
