### ISSUE TITLE
Interval does not work

### ISSUE THREAD

**Issue by botway** [nexus-js/ui#134]
Interval doesn't repeat and doesn't auto-start with a default value (only when the third parameter is explicitly set to true), but then it fires only one time.

This line does not produce any console log
```javascript
var interval = new Nexus.Interval(100, function() {
  console.log('beep');
})
```

**Comment by joshreiss** [comment]
I'm getting the same problem
---
var interval = new Nexus.Interval(1000, function() {  console.log('beep'); })

_No output_

---
javascript:
`var interval = new Nexus.Interval(1000, function() {  console.log('beep'); })
interval.start();`

console:
`beep` _just once_
---
javascript:
`var interval = new Nexus.Interval(1000, function() {  console.log('beep'); },true)`

console:
`beep` _just once_

It used to work, so it seems like there might have been a change in Chrome (or some versions of Chrome) recently that affects the Nexus interval.

**Comment by vladansaracpv** [comment]
Because of the Autoplay policy changes, AudioContext must be resumed after user interacted with page. As Nexus clock uses AudioContext for timing, you'd have to do it somewhat like this:
```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/nexusui@2.0.13/dist/NexusUI.min.js"></script>
  </head>
  <body>
    <div id="target"></div>

    <script>
      document.addEventListener('click', () => Nexus.context.resume());
      var interval = new Nexus.Interval(500, () => console.log('beep'), true);
    </script>
  </body>
</html>
```

**Comment by tatecarson** [comment]
Yes, this is the solution. Thanks @vladansaracpv .
