### ISSUE TITLE
Nexus oscilloscope connect 

### ISSUE THREAD

**Issue by luisArandas** [nexus-js/ui#137]
Is it possible to have more than one oscilloscope connected to different things in the same context?
For example one for the main master and other one only for a synthesiser from tone.js?
Assuming Tone.context = Nexus.context;
Best, Luis

**Comment by tatecarson** [comment]
I am not sure if you can connect it to the master, `Tone.Master` doesn't seem to work anymore. I am not sure how to access it. But this code attaching oscillators to separate nodes does work: 

```
Tone.setContext(Nexus.context)

const tri = new Tone.Synth({
  oscillator:{
    type: "triangle"
  }
}).toMaster();

const test = new Tone.Synth({
  oscillator:{
    type: "triangle"
  }
}).toMaster();

const oscilTri = new Nexus.Add.Oscilloscope('#instrument')
oscilTri.connect(tri)

const oscilMaster = new Nexus.Add.Oscilloscope('#instrument')
oscilMaster.connect(test);
```
