### ISSUE TITLE
Trigger on Events

### ISSUE THREAD

**Issue by luisArandas** [nexus-js/ui#143]
Is it possible to fire an event when any of the widgets gets a change?
I have a ton of them but I don't want to print the same code in every 'change' function of nexus ui
Best, Luis

**Comment by taylorbf** [comment]
Hi Luis, the best way to do this is create all of your interfaces as properties of an object:

```javascript
var UI = {
  frequency: new Nexus.Dial('#frequency'),
  gain: new Nexus.Dial('#gain'),
  filter: new Nexus.Dial('#filter')
}
```

and then loop through the keys of that object to create a change listener for each one.

NexusUI doesn't keep track of the interfaces elements you have created or removed, so there is not really a way for us to apply event listeners to all of them on command. I suppose we could create a 'change' listener by default when any element is created, but then that listener would go unused most of the time.

I agree that it would be nice to have a method in the API for applying one 'change' function to all of the interface elements on the page. Open to any ideas for doing this. Right now it is up to the user to design it through managing their interface components in arrays or objects, and looping through them.

**Comment by luisArandas** [comment]
Thank you very much for the fast response!
That is an interesting way. But I would need an infinite for loop (perhaps I'm not seeing it clearly).
What do you mean of creating a change listener for each one?
Thanks in advance, Luis

**Comment by taylorbf** [comment]
Hi Luis, here's a codepen demonstrating what I meant:

[https://codepen.io/taylorbf/pen/daqwde](https://codepen.io/taylorbf/pen/daqwde)

You wouldn't need an infinite loop -- just one that loops through your array of NexusUI objects.

Hope this helps,
Ben

**Comment by luisArandas** [comment]
Thank you for your help and good solutions.
Best, Luis.
