### ISSUE TITLE
What's the difference between these two apis?

### ISSUE THREAD

**Issue by rohitkrishna094** [nexus-js/ui#149]
Take a look at this link: 
https://nexus-js.github.io/ui/api/#intro

and now take a look at this link:
http://nexusosc.com/api/#nexusui-api-nx

What's the difference between two api's? Also why isn't `nx` api present in first link?

**Comment by tatecarson** [comment]
The second one is an older version of nexusUI that is no loner developed/supported. The docs were left up for a user that had just built a course using v1 but may be taken down soon.
