### ISSUE TITLE
error calling the sequencer component

### ISSUE THREAD

**Issue by Gugu04** [nexus-js/ui#167]
I find myself using NexusUI with React.js through the implementation of **npm** "nexusui": "2.0.10"

**ReferenceError: Nexus is not defined**
C:/lib/interfaces/sequencer.js:201
**> 201 | this.interval = new Nexus.Interval(200,function() {},false); // jshint ignore:line**

![Captura de pantalla (23)](https://user-images.githubusercontent.com/54090651/74950901-6cf6d580-53c5-11ea-94ae-795703b90e03.png)
![ok1](https://user-images.githubusercontent.com/54090651/74950925-754f1080-53c5-11ea-8edf-e86b588c2705.PNG)

I've been calling in different ways, but the same error keeps sending me.

If I delete the line
**this.interval = new Nexus.Interval (200, function () {}, false); // jshint ignore: line**

with html and javascript without any framework the component still works and does not send an error.
but in React I can't find a solution I hope and someone can help me

**Comment by rohitkrishna094** [comment]
I think you should have an import like this.

`import Nexus from 'nexusui';`

Can you try this and let me know?

**Comment by Gugu04** [comment]
It does not work, the same error appears.
I also made this import but it didn't work

`import {Sequencer} from 'nexusui';`

that this serious by component

**Comment by rohitkrishna094** [comment]
I think you should add nexus ui script in index.html. For example add this in your body tag of index.html file under public folder.

`<script src="https://rawgit.com/nexus-js/ui/master/dist/NexusUI.js"></script>`

**Comment by Gugu04** [comment]
Thanks friend, the component has already worked

**Comment by rohitkrishna094** [comment]
Oh that's great. I am just curious. Can I know how you fixed it? Thanks

**Comment by Gugu04** [comment]
Simply add the script in the index.html file found in the directory called public.

![Captura de pantalla (6)](https://user-images.githubusercontent.com/54090651/74998297-02be4f00-541e-11ea-882d-ecf015e89111.png)

I really don't know why it works, since I placed NexusUI as a dependency to download the files using npm this should work as a native and not declare the script. Thanks

**Comment by tatecarson** [comment]
Thanks @rohitkrishna094 for your input. It seems like this is solved so i'm closing it.
