### ISSUE TITLE
document.write ignored when loading the script asynchronously

### ISSUE THREAD

**Issue by anselbobrow** [nexus-js/ui#186]
Since browsers disabled audio contexts that are not initialized by a user interaction, it is useful to load libraries like NexusUI and Tone.js through scripts added asynchronously via js. One of the minor issues this causes with Nexus is a [document.write statement](https://github.com/nexus-js/ui/blob/master/dist/NexusUI.js#L181) that throws a warning in Chrome because (from to the [MDN spec](https://developer.mozilla.org/en-US/docs/Web/API/Document/write)):

> document.write in deferred or asynchronous scripts will be ignored

I think the quickest fix here would be to use createElement() instead.

**Comment by mscottnelson** [comment]
It sounds like you have a handle on the issue. Any interest in submitting a PR?

**Comment by anselbobrow** [comment]
Sure, will do.

**Comment by tatecarson** [comment]
Is this fixed with #191?

**Comment by pendragon-andyh** [comment]
Yes. This issue was the reason for submitting or #191
