### ISSUE TITLE
Github pages not showing newest docs

### ISSUE THREAD

**Issue by tatecarson** [nexus-js/ui#194]
This is driving me a little nuts. Does anyone know why GitHub pages is not showing the most recent changes to the docs? It should just work, right? I can see [here](https://github.com/nexus-js/ui/deployments/activity_log?environment=github-pages) that it hasn't build since march.

**Comment by pendragon-andyh** [comment]
For nexusUI, I always assumed that you just need to merge the master branch to the gh-pages branch.

Personally for my project, I always use the gh-pages mom package (see [this package.json](https://github.com/pendragon-andyh/junox/blob/master/package.json))

**Comment by pendragon-andyh** [comment]
Thanks for merging my PRs. Is there any other issues that you would like me to look at?

**Comment by tatecarson** [comment]
Really any you think you can fix. I really appreciate it. I am trying to finish a PhD and I only have time to review PRs, which I guess was Ben's issue too.

**Comment by tatecarson** [comment]
> For nexusUI, I always assumed that you just need to merge the master branch to the gh-pages branch.

This worked. I haven't updated the docs since I took over from Ben and I thought that it would build automatically because that's how GHpages does it now. 
> 
> Personally for my project, I always use the gh-pages mom package (see [this package.json](https://github.com/pendragon-andyh/junox/blob/master/package.json))
