### ISSUE TITLE
this.parent.style is undefined

### ISSUE THREAD

**Issue by MinionMax** [nexus-js/ui#197]
trying to create an oscilloscope connected to my tone.js synth.
throws this error:
`var oscilloscope = new Nexus.Oscilloscope('.oscilloscope-container',{
    'size': [300,150]
})
oscilloscope.connect(Tone.Destination);
`
`Uncaught TypeError: this.parent.style is undefined
    parseSettings interface.js:86
    Interface interface.js:19
    Oscilloscope oscilloscope.js:29`
the parrent div's style is defined so I reaally don't know where this is coming from

**Comment by marcelblum** [comment]
The constructor expects either an element id string or element object in the first argument, so a selector like your `'.oscilloscope-container'` wouldn't work. You probably want
`var oscilloscope = new Nexus.Oscilloscope(document.querySelector('.oscilloscope-container'),{ 'size': [300,150] }) `
But also note that it's a little tricky to use with the latest version of Tone, you'll need to first set Nexus to use Tone's audio context which is complicated by latest Tone's use of [standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context). So you have to do:
`Nexus.context = Tone.getContext().rawContext._nativeAudioContext`
And then after you create the oscilloscope object,
`oscilloscope.connect(Tone.Destination._internalChannels[1]._nativeAudioNode)`

**Comment by MinionMax** [comment]
OMG Yesssss. You have no idea how long I've been trying to create an oscilloscope, just discovered your library and now it works! Thank you so muchh. May I suggest an update in the doc, taking the new connect syntax into account?

**Comment by tatecarson** [comment]
Thanks, @marcelblum  for answering. I'm going to close this now, let us know if you have any other issues @MinionMax.

**Comment by marcelblum** [comment]
For the record it's not my library, just trying to help with an issue I struggled with for a bit when Tone updated recently.
