### ISSUE TITLE
Keyboard range settings

### ISSUE THREAD

**Issue by jesseallison** [nexus-js/ui#21]
It would be much more flexible to have a midi base pitch combined with the number of pitches for the keyboard as opposed to strict octaves.  This would allow a keyboard to start on a low A and run for 88 keys.  It would also need to shift the pattern of white and black keys to accommodate the alternate starting pitch

**Comment by taylorbf** [comment]
You can set the low & high keys of a Piano interface in version 2. b03b8f6ea20e9d184e466b91c8475c065a676af1
