### ISSUE TITLE
How can I use nexusui with nextjs?

### ISSUE THREAD

**Issue by rohitb8-oodles** [nexus-js/ui#221]

**Comment by jamesstaub** [comment]
I don't have experience with nextjs but I have implemented nexus ui elements in my Ember js app, maybe it will be helpful

I created a [nexus modifier](https://github.com/jamesstaub/euclip/blob/master/app/modifiers/nexus-ui.js) which gets added like an attribute on a `div`

The modifier is ember's way of manipulating a DOM element after it renders in a component. Maybe NextJs has a similar API for manipulating a DOM element when it rendeers.

Then I apply the modifier to a div in [in my component](https://github.com/jamesstaub/euclip/blob/master/app/components/controls/number-box.hbs)
