### ISSUE TITLE
Web components

### ISSUE THREAD

**Issue by taylorbf** [nexus-js/ui#35]
The dev branch now has a folder **/webcomponents** which has an example of a nexusUI dial invoked as a web component:

``` html
<nx-dial></nx-dial>
```

However, I have some concerns about using this method. 

The browser actually renders the component as this:

``` html
<nx-dial>
  <canvas id="dial1"><canvas>
</nx-dial
```

I worry that users will have less transparent access to the underlying canvas, for example if they want to animate it with jQuery or get its style. If a user alters the `<nx-dial>` using JS, we need to make sure certain altered properties (like width/height) are transferred to the inner canvas, and vice versa. 

I will read more on this subject but it is worth a brainstorm / discussion for now as to whether we really want to pick up this approach.

The syntax is actually only negligibly shorter, since we can't use `<dial>` and must use `<nx-dial>` or another hyphenated name.

**Comment by taylorbf** [comment]
One advantage of using web components is that we could combine widgets within web components. For example, this would be a logical step --

written:
```html
<nx-dial label="volume" number=true></nx-dial>
```

rendered as:

```html
<nx-dial label="volume" number=true>
  <canvas nx="dial"></canvas>
  <canvas nx="number"></canvas>
  <canvas nx="comment"></canvas>
</nx-dial>
```

in this case, one `<nx-dial>` declaration produces a collection of nexusUI elements:
- a dial
- a number to show the dial's value
- a comment to label the dial as "volume"

**Comment by rchrdnsh** [comment]
If you switch to SVG from canvas then this might work better? The styling of web components is still in the early stages, and CSS custom properties are landing browsers, while @apply is not quite there yet...but overall I think WC's are the right approach in general :-)

**Comment by taylorbf** [comment]
I decided not to pursue web components, because it still requires a polyfill, seems less accessible to style/customize, and would require considerably more time. 

If anyone would like to pursue porting nexusUI to web components, I'm happy to answer any questions or help in any way I can.
