### ISSUE TITLE
Button image on load

### ISSUE THREAD

**Issue by AKa-visuals** [nexus-js/ui#55]
Hi Im trying to load an ui made with buttons and to use an image for everybutton , so i use
the button.setImage( src) method, the problem is that it does not show the images when i load the page , it show the images only after you click in the buttons, what im doing worng?
any way to load images on toggles too?
thanks!

**Comment by taylorbf** [comment]
Hi @AKa-visuals, thanks for finding this bug. It was a simple context issue (the draw function was called without the correct context.) I just fixed and updated.

**Comment by AKa-visuals** [comment]
Cool men! i post you my first release on vvvv about nexus ui editor, still some bugs but really functional for the comunnity, lets keep in touch.!
http://vvvv.org/contribution/nexus-ui-4v

**Comment by taylorbf** [comment]
Version 2 no longer supports image buttons. This was a sacrifice but I think in the best interest of having a small core set of interfaces which are maintainable.

The Nexus editor you made is awesome!
