### ISSUE TITLE
Bug in keyboard I think

### ISSUE THREAD

**Issue by joearms** [nexus-js/ui#58]
Either this code is wrong:

```
<script src="./nexusUI.js"></script>
<body></body>
<script>
  nx.add("keyboard",{name:'key', w:600});

  nx.widgets["key"].on('*', function(data) {
      console.log('data', data);
  })
</script>
```

Or the documentation is wrong

When I run this in chrome and look in the console I see something like this

data Object {on: 12, note: 62, midi: "62 1"}
bug.html:7 data Object {on: 0, note: 62, midi: "62 0"}
bug.html:7 data Object {on: 12, note: 64, midi: "64 1"}
bug.html:7 data Object {on: 0, note: 64, midi: "64 0"}
bug.html:7 data Object {on: 12, note: 65, midi: "65 1"}
bug.html:7 data Object {on: 0, note: 65, midi: "65 0"}
bug.html:7 data Object {on: 13, note: 67, midi: "67 1"}
bug.html:7 data Object {on: 0, note: 67, midi: "67 0"}

The documentation says on should be 0 or 1 but I more or less arbitrary non zero values

**Comment by aberkow** [comment]
I get the same thing, but I think the documentation is a little misleading. When I log `data` in chrome, the values aren't random. They look like velocity signals. The higher you go on the key, the larger the value.

**Comment by taylorbf** [comment]
Version 2: The new [Piano](http://nexus-js.github.io/ui/api/#Piano) interface responds with *note* (midi note) and *state* (true or false) values.
