### ISSUE TITLE
Need to be able to change 'nx' attribute name

### ISSUE THREAD

**Issue by hepiyellow** [nexus-js/ui#59]
Hi,
I am trying to use nexusUI component with React. 
React uses JSX, and it ignores any custom HTML attributes. So the 'nx' attribute on canvas element is not rendered.
To go around that, React passes through attributes prefixed with 'data-'

It would be a good idea that the canvas attribute name ('nx') used for nexus components would be settable.
I see it is used in the manager.transform function (and some other places).

I've trying changing the manager.transform function, and making it use 'data-nx', and it works.

Thanks,
Erez

**Comment by Lokua** [comment]
Ran into this issue, too.

**Comment by mkw2000** [comment]
@hepiyellow What exactly did you change to get it to work? I'm having this issue and can't get it working

**Comment by hepiyellow** [comment]
I don't remember anymore exactly (and can't find my changed code)
but it started with manager.js
with the line:
`var nxType = canvas.getAttribute("nx");`

which need to change to something like:
`var nxType = canvas.getAttribute("data-nx");`

And then in your HTML when you add canvas components you need to add the `data-nx` attribute, instead of `nx`.

There might be other places where you need to replace `nx` with `data-nx`.
I see now that in manager.js there is also a blockMove function which checks for the `nx` attribute.
Maybe you need to change that too, but I am not so much familiar with this code. and haven't tried that.

**Comment by hepiyellow** [comment]
There is a workaround the 'nx' attribute issue.
See https://github.com/lsu-emdm/nexusUI/issues/65

**Comment by taylorbf** [comment]
You can now customize the attribute that NexusUI looks for when it transforms a group of elements, when using Nexus.Rack in version 2. See the Rack tutorial: [http://nexus-js.github.io/ui/api/#rack](http://nexus-js.github.io/ui/api/#rack). Thanks @hepiyellow for noticing this need.
