### ISSUE TITLE
Metroball freezes browser window (chrome) when balls drawn too far out of bounds

### ISSUE THREAD

**Issue by dsholmes** [nexus-js/ui#60]
quick fix - just limited the range of the ball x position to the widget width

metroball.prototype.addNewMB = function(ballpos) {
    var nextIndex = this.CurrentBalls.length;
        ballpos.x = Math.max(0, Math.min(this.GUI.w, ballpos.x));
    this.CurrentBalls[nextIndex] = new this.Ball(nextIndex, ballpos.x, ballpos.y, this);
}

**Comment by taylorbf** [comment]
Thanks Danny! I will make this fix.

Side note -- as a shorthand for

ballpos.x = Math.max(0, Math.min(this.GUI.w, ballpos.x));

nexusUI has a function:

ballpos.x = nx.clip(ballpos.x, 0, this.GUI.w)

which would limit ballpos.x to numbers between 0 and this.GUI.w

On Fri, Mar 18, 2016 at 9:25 AM, Danny Holmes <notifications@github.com>
wrote:

> quick fix - just limited the range of the ball x position to the widget
> width
>
> metroball.prototype.addNewMB = function(ballpos) {
> var nextIndex = this.CurrentBalls.length;
> ballpos.x = Math.max(0, Math.min(this.GUI.w, ballpos.x));
> this.CurrentBalls[nextIndex] = new this.Ball(nextIndex, ballpos.x,
> ballpos.y, this);
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lsu-emdm/nexusUI/issues/60>
>



-- 
Ben Taylor
Digital Media Programming
@ Goucher College Digital Arts
whitechord.org

**Comment by taylorbf** [comment]
Metroball is no longer a component in version 2. The metronome mechanism was replaced with the more general [Nexus.Interval](http://nexus-js.github.io/ui/api/#interval). Once again this was a product of trying to make a more flexible core that is more reliable and maintainable.
