### ISSUE TITLE
Customize controls

### ISSUE THREAD

**Issue by Deschutter** [nexus-js/ui#62]
Hi!

I want to customize the sliders and knobs, how do I use a png image to replace the default "skin"?

Thanks!

E.D.

**Comment by taylorbf** [comment]
Hello! Sorry for not replying to this when you asked it.

There is not currently a way to use an image to skin the components. You can change their color using .colorize(), but that is about it.

I'll add ImageButton, ImageDial, ImageSlider to a list of possible future interfaces.
