### ISSUE TITLE
Metroball has issues rendering label, tracks events on label area

### ISSUE THREAD

**Issue by sathran** [nexus-js/ui#64]
Hi,

The metroball component has some issues when rendering labels.
Also, when a label is rendered, it appear the space used by the label is not being discarded when tracking user interactions, which can lead to some odd results:

![image](https://cloud.githubusercontent.com/assets/1090355/20970302/ce64d848-bc84-11e6-867c-eb12cef098ed.png)

Keep up the great work, guys! :)

**Comment by taylorbf** [comment]
Sorry for this! Yes that was a really buggy interface that has been replaced by a more general [`Nexus.Interval`](http://nexus-js.github.io/ui/api/#interval) metronome in Version 2.
