### ISSUE TITLE
Changing keyboard key colors

### ISSUE THREAD

**Issue by cesar3dartist** [nexus-js/ui#69]
Is there a way to define the colors of the "white" and "black" keys on the keyboard?

**Comment by cesar3dartist** [comment]
Found how to do it for the whites...

keyboardA.colors.fill = "#777777";

**Comment by cesar3dartist** [comment]
And to do it for the blacks:

keyboardA.colors.black = "#00FF00";

**Comment by cesar3dartist** [comment]
I take that back..the "fill" just fills the object with a color on top.
I don't really know how to change the color of the white keys...
Anyone?

**Comment by taylorbf** [comment]
Hey there @cesar3dartist, thanks for responding with some answers here. Yes, `.fill` is intended to be the white key colors. Try this and let me know if it's what you're after --

```
keyboardA.colors.fill = "red"
keyboardA.colors.borderhl = "blue"
keyboardA.colors.black = "yellow"
keyboardA.draw()
```

**Comment by cesar3dartist** [comment]
![keyboard](https://cloud.githubusercontent.com/assets/25041620/22723687/4e08000e-ed75-11e6-99ae-a2941311b7c7.JPG)

**Comment by cesar3dartist** [comment]
That works. Thanks a bunch!
Is there a way to increase the "lines" between the keys?
In the interface I'm using, the lines are not thick enough to see them.

**Comment by adowty** [comment]
...also, I need to change the color of selected keys separate from the border.
keyboardA.colors.borderhl = "blue"
in "toggle" mode when i select a c major scale, the keys all become one big blue rectangle.

**Comment by adowty** [comment]
...sorry, i meant when in "toggle" mode.

**Comment by adowty351** [comment]
Thinking this through, I am going to need to be able to define the:
white keys on color, 
white keys off color, 
white keys outline, 
black keys on color, 
black keys off color, 
and black keys outline 
...all individually.

**Comment by mscottnelson** [comment]
Unfortunately, this level of style customization is not currently supported by NexusUI. However, you can still access some aspects of styling by using CSS to access the child elements of a parent id. For example:
https://codepen.io/mscottnelson/pen/YYyGzo

**Comment by michaelkolesidis** [comment]
> Hey there @cesar3dartist, thanks for responding with some answers here. Yes, `.fill` is intended to be the white key colors. Try this and let me know if it's what you're after --
> 
> ```
> keyboardA.colors.fill = "red"
> keyboardA.colors.borderhl = "blue"
> keyboardA.colors.black = "yellow"
> keyboardA.draw()
> ```

Hey thanks for your answer. I have a problem with this approach, I'm getting an "Uncaught TypeError: keyboard.draw is not a function" error. Do you have any idea why is this happening? Thanks!
