### ISSUE TITLE
NexusUI present & future

### ISSUE THREAD

**Issue by taylorbf** [nexus-js/ui#73]
Sharing a quick note about NexusUI's present & future --

When we (Jesse Allison and myself) developed NexusUI in 2012/2013, it was designed with a fairly experimental / hacker-y mindset, as a research project in an experimental music program. The original design goal was to create interfaces that could be embedded with equal compatibility in many different environments — mobile apps, web, Max/MSP. Its primary use (in our department) was to enable students to quickly hack together music instruments for mobile phones. 

With the rise of web audio in the last few years, the use of the library has really transformed. Unfortunately, since graduating, I have not been able to keep the library up-to-date with those changing needs. But I am now in a position to do so, and I am taking this chance to reconsider the scope of the library and many of its core features.

I am updating / rewriting the library to focus on web audio applications. It will be designed to fit one of its most common current uses: as a toolkit to help build interactive web audio instruments. Can it still be used as a mobile interface for Max projects, communicating via OSC? Yes, and I'll share updated templates for that ability. But the standard design patterns will assume an integration with web audio. I am additionally taking this chance to provide a stabler and cleaner code base for the project.

In some ways, this revision will not be all that different from how the library appears now. But there will be key differences:

- SVG graphics instead of canvas graphics
- More conventional Javascript API (no global variable declarations)
- Revised interfaces, focused on musicality & functionality rather than experimentation & novelty
- More accurate timing methods using a web audio context
- A few methods for handling scales / tuning (but not a full Teoria competitor)
- Revised docs with more code examples and tutorials
- Codebase => ES6 (babel/webpack)

This revision is about 50% complete. I don't want to put a release timeline here but I certainly hope to share it in the next month or two.

So, what does this mean for NexusUI now? For existing bugs (of which there are many), I have taken note and am focusing on fixing them in this update. I also welcome input if you would like to get in touch about the design of this update.

I hope this revision can help make NexusUI a more useful, flexible, and relevant project in the coming years.

**Comment by rchrdnsh** [comment]
Web Components! Please please please! XD Custom Element and Shadow DOM the bejeezzus out of this lib!

**Comment by truthcollins** [comment]
Another somewhat similar project is Open Stage Control.  Perhaps there could be compatibility between them?  Bi-directional OSC & networked MIDI for non-audio control interfaces would be great.

**Comment by truthcollins** [comment]
Or make it compatible with Fugio.   http://www.bigfug.com

**Comment by taylorbf** [comment]
A little later than planned but this update is now live. It is more stripped-down than the previous version, but I think it will ultimately be more useful and reliable.

[http://nexus-js.github.io/ui/](http://nexus-js.github.io/ui/)

**Comment by Enteleform** [comment]
@taylorbf 

> Can it still be used as a mobile interface for Max projects, communicating via OSC? Yes, and I'll share updated templates for that ability.

Are these templates available? I've tried searching for them but haven't found anything.
