### ISSUE TITLE
Dynamically added widgets don't emit values

### ISSUE THREAD

**Issue by turbo5** [nexus-js/ui#78]
My setup: I add all the widgets from code, with `nx.add`. Then, in the `nx.onload` I set the possible props, such as initial value, min, max, row, etc. After this, I set the `.on` callback for handling the emitted values, catching everything ('*').
After all of this I call `.init()` on all of them just in case, because I have seen it on the main page :) (referring back to the outdated documentation issue, it would be also good to include, in which cases the init() or the draw() should be called.)

This approach works with some widgets; by working I mean they function seemingly perfect, also emitting the values to the callback func. But for some widgets, the latter is missing, the callback func is not called, therefore I can't use the values they provide. They do work when added to html though.

What I've tried so far:
Work: button, slider, matrix
Doesn't work: position, string, multislider

Any help is appreciated, thanks!

**Comment by taylorbf** [comment]
Hi @turbo5 , in the version 2 [update](http://nexus-js.github.io/ui/), interfaces are now added using a constructor, i.e.:

```js
var dial = new Nexus.Dial( '#target', ... settings ... );

dial.on('change',function(value) {
   console.log(value);
}) 
```

You ought to be able to add any interfaces like this, dynamically, and set up event handlers for them.
