### ISSUE TITLE
Setting initial values

### ISSUE THREAD

**Issue by kentskyo** [nexus-js/ui#79]
Perhaps this is a feature request, but I would like to be able to set an initial value for a widget like a slider or dial?!

**Comment by taylorbf** [comment]
In Version 2, you can now set initial value as part of the options when creating most interfaces. 

Check out the [Slider docs](http://nexus-js.github.io/ui/api/#Slider) as an example. In the "With Options" section, there is an option for 'value', which is the initial value of the slider.
