### ISSUE TITLE
documentation of matrix row and col switched

### ISSUE THREAD

**Issue by zingzog** [nexus-js/ui#80]
In the documentation page (http://www.nexusosc.com/api/#nexusui-api-matrix) it says:
//Turn on the cell at row 1 column 2
matrix1.matrix[1][2] = 1
matrix1.draw()

What this actually does is //Turn on the cell at column 1 row 2
row and column are switched. It is the same for the turn off example

**Comment by taylorbf** [comment]
Thanks for the heads up! This should be fixed in Version 2.

BTW, Matrix was relabelled as Sequencer, and the docs are [here](http://nexus-js.github.io/ui/api/#Sequencer).
