### ISSUE TITLE
Center-relative sliders?

### ISSUE THREAD

**Issue by willurmston** [nexus-js/ui#81]
It would be great if there was a centered option for the horizontal and vertical sliders, similar to a pitchbend wheel on synthesizers. I couldn't find a way to do that but I may have missed it!

**Comment by taylorbf** [comment]
This is a cool idea ... a slider that gradually re-centers itself. I'll add a 'pitchbend' interface onto my running list of potential future interfaces, but I can't guarantee when those will be created.

However, I think this might be something that you could do through customizing your interface --

Try something like this: set up an [animation interval](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). If the slider's value is more than 0 or less than 0, have the slider's value move a little bit closer to 0. That ought to accomplish the core goal, yes?
