### ISSUE TITLE
Remove value text from slider

### ISSUE THREAD

**Issue by chkworks** [nexus-js/ui#82]
I really hope, this is already possible within your lovely framework - can I remove the output value of a slider from the canvas? I want to place and style it somewhere else through the returned value.

Thanks in advance! :)

**Comment by taylorbf** [comment]
In version 2, sliders no longer show a value automatically, however [they can be linked to an interactive number box](http://nexus-js.github.io/ui/api/#sync) which does show their value.

Thanks for the tip -- I agree it's important to not always show the number information.
