### ISSUE TITLE
Chrome 59 Warning on "Select" widget

### ISSUE THREAD

**Issue by japentaca** [nexus-js/ui#85]
First of all, congrats for version 2, it's true common sense now. Very practical.

Problem:
After clicking in a select wiget, Chrome 59 reports this warning on console:
----
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
----
It also happens on older versions of Nexus.

It's not causing any problems by now, but I always do the report because of the "Violation" level.

**Comment by mscottnelson** [comment]
I am unable to duplicate this in Chrome 64. Can you verify whether or not you are still receiving this message in your browser of choice? If you are indeed still getting this message, can you provide any other information about what I would need to do to duplicate? Thanks!

**Comment by japentaca** [comment]
It doesn't happen anymore.

Maybe was a Chrome 59 specific issue.

Thanks.
