### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by adowty351** [nexus-js/ui#87]
HI Guys, Love the reboot!
Is OSC on the schedule to be re-implemented in the future?

**Comment by taylorbf** [comment]
Thanks!

No, we've separated the client-side and server-side aspects of this project. NexusUI is focused on being a front-end framework for rapidly prototyping web audio instruments (or anything else that uses analog-synth-style controls : ) . Maintaining all of the different server paradigms got very difficult.  

There are other frameworks for OSC communication that I recommend integrating with -- in fact they are much better than what we had previously in NexusUI. The [Rhizome Server](https://github.com/sebpiq/rhizome) project is great if you want to send OSC using node.js and websockets. I think there are a variety of osc.js implementations but I'm not sure which are current. I know Jesse (of NexusUI team) is working on NexusHub, a server for OSC communication, but I think it is still underway.

**Comment by truthcollins** [comment]
Open Stage Control has a server feature
https://github.com/jean-emmanuel/open-stage-control
