### ISSUE TITLE
Enhancement request: touch start/end events

### ISSUE THREAD

**Issue by thSoft** [nexus-js/ui#88]
It would be great if not only change, but also touch start and end events could be listened to. Example use case: I want to control a tone's frequency with a slider, but I want the sound to be played only when the user is dragging the slider (like [here](https://tonejs.github.io/examples/#oscillator)).

**Comment by thSoft** [comment]
By inspecting the source, I learnt that I can get the DOM element with `slider.element` and add event listeners directly to it. If this is intended to be the recommended usage (and not a workaround), feel free to close this issue. :)

**Comment by taylorbf** [comment]
Glad you found a workaround. Yes most interfaces have an `.element` property that you can interact with directly if you need to.

I like the idea of having more events (such as click and release). That is part of the rationale for using the `.on()` paradigm, even though most interfaces only have a 'change' event right now -- I hope more events will be added in the future. I'll look at adding this in the next round of updates.

**Comment by taylorbf** [comment]
I did implement a basic version of this. It is only functional for some of the interfaces -- basically the simpler ones (dial, slider, button, toggle, position, number and a few others). 

See documentation in the [API](http://nexus-js.github.io/ui/api/#intro) - scroll down to where it talks about Listening for Interaction Events.

**Comment by thSoft** [comment]
Great, thanks!
