### ISSUE TITLE
Connecting oscilloscope with audio using tone.js and nexus ui

### ISSUE THREAD

**Issue by nmwenz90** [nexus-js/ui#90]
Hi,

 I'm trying to figure out why my oscilloscope isn't working with my audio. I tried using the .connect(node) from the api but it's still not working for me. What i get back when i run the console is "InvalidAccessError: Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context."

here's the body of my html file

`   <body style="background-color:aquamarine;">
        

        <div id="button"></div>
        <div id="visualizer"></div>
        <canvas id="waveform" width=600 height="200"></canvas>
        
        <script>
            
      	//analyse the frequency/amplitude of the incoming signal	
		var fft = new Tone.Analyser("fft", 32);
        
		//get the waveform data for the audio
		var waveform = new Tone.Analyser("waveform", 1024);  
            
        var player = new Tone.Player ({
            "url" : "https://res.cloudinary.com/dvwvkt7iq/video/upload/v1502945343/fake_aah_qxkkcr.wav",
            "loop" : true
            
        })
       
            player.fan(fft,waveform);
            player.toMaster();
            

            

        var button = new Nexus.Button('#button',{
            'size': [80,80],
            'mode': 'aftertouch',
            'state': false
        })
            
            button.on('change', function(){
                if (button.state === true){
                    player.start();
                }
                
                else{
                    player.stop();
                }
                
            });
	 // start it right away
            
//        var canvas = document.getElementById('tutorial');
//        var ctx = canvas.getContext('2d');
            
 
            var graphic = new Nexus.Oscilloscope('#visualizer')
            
            graphic.connect(waveform);
            
        </script>
        
    </body>`

To see more go to:
https://nmwenz90.github.io/oscilloscope-test/

I'm new to javascript and apis help would be greatly appreciated.
Thanks!

**Comment by taylorbf** [comment]
See the very recent issue #89 . Let me know if that helps you solve this. 

I'll leave this issue open until I get this in the documentation, which is clearly needed!

**Comment by nmwenz90** [comment]
Yes this worked thanks so much!!!

**Comment by taylorbf** [comment]
There is now clearer documentation about this in the description for the .connect() method of each audio visualization.
