### ISSUE TITLE
WebPack import error

### ISSUE THREAD

**Issue by AndrejHronco** [nexus-js/ui#95]
When importing Nexus from 'nexusui' or Nexus = require('nexusui') i get an error: 'Uncaught TypeError: Class extends value #<Object> is not a constructor or null'

What am i doing wrong?

**Comment by taylorbf** [comment]
Hi @AnrejHronco, thanks for catching this. Would you mind posting an example to github? If you are using a stack that is not really postable, then don't worry about it...

I have a guess of what is causing that error. I made a branch that implements the change. The branch is called import-test. Would you mind trying it out? You would need to download that branch from github, copy the contents into a folder inside your project's node_modules, then require that module you just created, and see if it still throws the error you mentioned?

**Comment by perbyhring** [comment]
Hi,

Looks to me like the problem is just that "index.js" is defined as "main" in package.json.
If I change "index.js" to "dist/NexusUI.js", I can import it without trouble.

When imported like this, Nexus also gets added to `window.Nexus` though.

**Comment by taylorbf** [comment]
Thanks @perbyhring, I have published that change. 

I would welcome a PR of index.js that does not add it to `window` when imported as a module. I tried a few strategies but did not have any luck in the time allotted.

**Comment by AndrejHronco** [comment]
Thanks for fixing this. works as expected now!
